# Generated by Django 3.1.8 on 2021-05-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
